# .pre-commit-hooks.yaml
- id: generate-sbom
  name: Generate and Compare SBOM
  description: >-
    Generate an SBOM using Anchore Syft and
    compare it with the baseline using sbomdiff.
  entry: scripts/generate_and_compare_sbom.sh
  language: python
  additional_dependencies: ["sbomdiff"]
  pass_filenames: false
  always_run: true
