---
# used for running pre-commit checks
name: pre-commit checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows manual trigger as well
  workflow_dispatch:

jobs:
  pre_commit_checks:
    # avoid running check for dependabot PR's
    if: ${{ github.event_name != 'pull_request' ||
      github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: ${{ !cancelled() }}
