name: pre-commit autoupdate

on:
  schedule:
    # Runs every Tueday at 9:00 AM MT
    - cron: '0 9 * * 2'
  # Allows manual trigger as well
  workflow_dispatch:

jobs:
  pc-autoupdate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install pre-commit
        run: python -m pip install pre-commit
      - name: Run pre-commit autoupdate
        id: autoupdate
        run: |
          pre-commit autoupdate
      - name: Check for modified files
        id: check_modified
        run: |
          # Check if any files were modified by pre-commit
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes"
            echo "no_changes=false" >> "$GITHUB_ENV"
          else
            echo "nochanges"
            echo "no_changes=true" >> "$GITHUB_ENV"
          fi
      - name: Create Pull Request
        if: ${{ env.no_changes == 'false' }}
        uses: peter-evans/create-pull-request@v7
        with:
          branch: pre-commit-autoupdate
          title: "chore: auto-apply pre-commit fixes"
          body: "Automated update for pre-commit hook versions."
          commit-message: "chore: auto-apply pre-commit fixes"
