---
# used for running pre-commit checks
name: pre-commit checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre_commit_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install pre-commit
        run: python -m pip install pre-commit
      - name: Run pre-commit on all files
        id: pre_commit
        run: pre-commit run --all-files --color=always --show-diff-on-failure
        # Allow the workflow to continue even if pre-commit fails
        continue-on-error: true
      - name: Check for modified files
        id: check_modified
        run: |
          # Check if any files were modified by pre-commit
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes"
            echo "no_changes=false" >> "$GITHUB_ENV"
          else
            echo "nochanges"
            echo "no_changes=true" >> "$GITHUB_ENV"
          fi
      - name: Auto-commit fixes if there are changes
        if: ${{ env.no_changes == 'false' }}
        run: |
          git config --global user.name \
            "github-actions[bot]"
          git config --global user.email \
            "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: auto-apply pre-commit fixes"
          git push
      - name: Fail if no changes were made but pre-commit failed
        if: ${{ env.no_changes == 'true' &&
            steps.pre_commit.outcome == 'failure' }}
        run: |
          echo "Pre-commit checks failed, \
          and no changes were made. Failing the action."
          exit 1
